sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t fluentd_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t fluentd_precise  .
    - docker build  -f test/Dockerfile-debian8      -t fluentd_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t fluentd_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t fluentd_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t fluentd_centos6  .

script:
    - PORT=1000
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_trusty
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-ubuntu14.04

    - PORT=1001
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_precise
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-ubuntu12.04

    - PORT=1002
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_jessie
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-debian8

    - PORT=1003
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_wheezy
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-debian7

    - PORT=1004
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_centos7
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-centos7

    - PORT=1005
    - docker run -d -p 127.0.0.1:$PORT:24220  fluentd_centos6
    - curl http://127.0.0.1:$PORT/api/plugins.json -v -o result-centos6


    - echo "==> Validating the test results..."
    - grep 'monitor_agent' result-ubuntu14.04
    - grep 'monitor_agent' result-ubuntu12.04
    - grep 'monitor_agent' result-debian8
    - grep 'monitor_agent' result-debian7
    - grep 'monitor_agent' result-centos7
    - grep 'monitor_agent' result-centos6
