- name: Check if time is synchronized (ntp test)
  command: "timedatectl status"
  register: time_synchronization
  changed: false
  tags:
    - skip_ansible_lint

# ulimit needs full shell
- name: Register number of file descriptors
  shell: "ulimit -n"
  register: file_descriptors
  changed: false
  tags:
    - skip_ansible_lint

- name: Fail on desynchronized time
  fail:
    msg: "Synchronize time with NTP. Follow instructions at https://docs.fluentd.org/v0.14/articles/before-install"
  when: "{{ not time_synchronization.stdout_lines[5].split(': ')[1]|bool }}"

- name: Fail on too small number of file descriptors
  fail:
    msg: "Increase number of file descriptors to more than 1024. Follow instructions at https://docs.fluentd.org/v0.14/articles/before-install"
  when: file_descriptors.stdout < 1025
