---
# file: tasks/use-yum.yml
#
# Configure td-agent from YUM repository.  
#
# @see http://docs.fluentd.org/articles/install-by-rpm
# @see http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh
#


- name: install libselinux-python binary for Ansible to work 
  sudo: True
  yum: name=libselinux-python state=present


- name: download installer script
  get_url: url=http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh  dest=/tmp/install.sh

- name: add executable permission to installer
  file: path=/tmp/install.sh  mode="a+x"

- name: remove "sudo" in the installer script
  lineinfile: dest=/tmp/install.sh  regexp="^sudo -k"  line="#sudo -k"

- name: remove "sudo" in the installer script
  lineinfile: dest=/tmp/install.sh  regexp="^sudo sh(.+)"  line="sh\1"  backrefs=yes

- name: install
  sudo: True
  shell: /tmp/install.sh





- name: install gcc and libcurlXXX for compiling plugins
  sudo: True
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - libcurl
    - libcurl-devel


- name: set INIT status (SysV style)
  sudo: True
  action: shell chkconfig --add td-agent
  action: shell chkconfig --level 345 td-agent on
